classdef (Abstract) Renderer < handle
% Renderer: generic renderer class
%
% Author: Paulo Pagliosa
% Last revision: 31/08/2024
%
% Description
% ===========
% The abstract class Renderer encapsulates the behavior of a generic
% renderer. Every renderer has axes that hold the graphic primitives
% generated by the renderer.

%% Public read-only properties
properties (SetAccess = private)
  axes;
end

%% Public methods
methods
  function showAxes(this, flag)
  % Shows/hides the axes of this renderer
    if nargin > 1 && ~flag
      flag = 'off';
    else
      flag = 'on';
    end
    axis(this.axes, flag);
  end

  function savePdf(this, filename)
  % Saves the image generated by this renderer as PDF
    f = get(this.axes, 'Parent');
    saveas(f, filename, 'pdf');
  end
  
  function savePng(this, fileName)
  % Saves the image generated by this renderer as PNG
    f = get(this.axes, 'Parent');
    saveas(f, fileName, 'png');
  end
end

%% Protected methods
methods (Access = protected)
  function this = Renderer(axes)
    this.axes = axes;
  end

  function h = drawPoint(this, p, color, marker, size)
    h = line('Parent', this.axes, ...
      'XData', p(:, 1), ...
      'YData', p(:, 2), ...
      'ZData', p(:, 3), ...
      'LineStyle', 'none', ...
      'MarkerFaceColor', color, ...
      'MarkerEdgeColor', color, ...
      'Marker', marker, ...
      'MarkerSize', size, ...
      'HitTest', 'off');
  end

  function h = drawLine(this, p, color, style, width)
    h = line('Parent', this.axes, ...
      'XData', p(:, 1), ...
      'YData', p(:, 2), ...
      'ZData', p(:, 3), ...
      'Color', color, ...
      'LineStyle', style, ...
      'LineWidth', width, ...
      'HitTest', 'off'); 
  end
end

%% Protected static methods
methods (Access = protected, Static)
  function setPointPropertiess(h, props)
    set(h, ...
      'MarkerFaceColor', props.color, ...
      'MarkerEdgeColor', props.color, ...
      'Marker', props.shape, ...
      'MarkerSize', props.size);
  end

  function setLineProperties(h, props)
    set(h, ...
      'Color', props.color, ...
      'LineStyle', props.style, ...
      'LineWidth', props.width);
  end
end

end % Renderer
